// ============================================================
//  commands/completion.rs — iloc completion <shell>
//
//  Generates shell completion scripts for Bash, Zsh, and PowerShell.
//  The scripts are written to stdout so the user can pipe them
//  into the appropriate location:
//
//    Bash:
//      iloc completion bash >> ~/.bash_completion
//      # or into the system dir:
//      iloc completion bash | sudo tee /etc/bash_completion.d/iloc
//
//    Zsh:
//      iloc completion zsh >> ~/.zfunc/_iloc
//      # ensure ~/.zfunc is in $fpath (add to ~/.zshrc):
//      # fpath=(~/.zfunc $fpath); autoload -Uz compinit && compinit
//
//    PowerShell (Windows PowerShell 5.1+ et PowerShell 7+/pwsh) :
//      iloc completion powershell >> $PROFILE
//      # puis: . $PROFILE
//
//  The completion covers all top-level subcommands, their flags,
//  and nested subcommand trees (sentinel, completion).
// ============================================================

use anyhow::Result;
use colored::Colorize;

#[derive(Debug, Clone, Copy)]
pub enum Shell {
    Bash,
    Zsh,
    PowerShell,
}

pub fn run(shell: Shell) -> Result<()> {
    let script = match shell {
        Shell::Bash       => bash_completion(),
        Shell::Zsh        => zsh_completion(),
        Shell::PowerShell => powershell_completion(),
    };
    println!("{}", script);
    Ok(())
}

pub fn run_setup(shell: Shell) -> Result<()> {
    let (script, instructions) = match shell {
        Shell::Bash       => (bash_completion(),       bash_setup_instructions()),
        Shell::Zsh        => (zsh_completion(),        zsh_setup_instructions()),
        Shell::PowerShell => (powershell_completion(), powershell_setup_instructions()),
    };

    println!();
    println!("{}", instructions);
    println!();
    println!("{}", "Generated script:".dimmed());
    println!("{}", "─".repeat(60).dimmed());
    println!("{}", script);
    Ok(())
}

// ── Bash completion ───────────────────────────────────────────

fn bash_completion() -> String {
    r#"# iloc bash completion
# Source this file or add it to /etc/bash_completion.d/iloc
# Generated by: iloc completion bash

_iloc_completions() {
    local cur prev words cword
    _init_completion || return

    local -r COMMANDS="init save undo log status sentinel selfinstall update share clone transfer-status dashboard completion studio hyperscale vault node login logout whoami config push pull cloud connect provider github vercel supabase deploy"
    local -r SENTINEL_CMDS="init enable disable status uninstall"
    local -r COMPLETION_SHELLS="bash zsh powershell"
    local -r HYPERSCALE_CMDS="push clone export status config node"
    local -r HYPERSCALE_CONFIG_CMDS="show init validate"
    local -r HYPERSCALE_NODE_CMDS="start stop status"
    local -r VAULT_CMDS="status migrate mirror backup verify"
    local -r VAULT_MIRROR_CMDS="add remove sync"
    local -r VAULT_BACKUP_CMDS="enable-cloud disable-cloud enable-hyperscale disable-hyperscale"
    local -r NODE_CMDS="join leave start status"
    local -r CONFIG_CMDS="cloud"
    local -r CONFIG_CLOUD_CMDS="add list use remove"
    local -r CLOUD_CMDS="usage gc doctor verify"
    local -r CONNECT_SERVICES="github vercel supabase"
    local -r STUDIO_CMDS="open"
    local -r PROVIDER_CMDS="init validate test install search publish list remove profile"
    local -r PROVIDER_PROFILE_CMDS="list use remove"
    local -r GITHUB_CMDS="list use status remove repo branch issue pr release actions secret collab webhook search"
    local -r VERCEL_CMDS="list use status remove deploy inspect project deployment env domain alias secret edge webhook check team"
    local -r SUPABASE_CMDS="list use status remove org project keys sql table extension migration function secret branch advisor"
    local -r GLOBAL_FLAGS="--help --version"

    # Top-level command
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$COMMANDS $GLOBAL_FLAGS" -- "$cur"))
        return 0
    fi

    local command="${words[1]}"

    case "$command" in
        save)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W '"<message>"' -- "$cur"))
            fi
            ;;

        undo)
            case "$prev" in
                --file)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    ;;
                *)
                    if [[ -f ".ilocker/iloc.db" ]] && [[ $cword -eq 2 ]]; then
                        local ids
                        ids=$(sqlite3 .ilocker/iloc.db \
                            "SELECT id FROM snapshots ORDER BY created_at DESC LIMIT 20;" 2>/dev/null)
                        COMPREPLY=($(compgen -W "$ids --file --help" -- "$cur"))
                    else
                        COMPREPLY=($(compgen -W "--file --help" -- "$cur"))
                    fi
                    ;;
            esac
            ;;

        log)
            COMPREPLY=($(compgen -W "--ids --help" -- "$cur"))
            ;;

        status)
            COMPREPLY=($(compgen -W "--health --help" -- "$cur"))
            ;;

        sentinel)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$SENTINEL_CMDS" -- "$cur"))
            fi
            ;;

        completion)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$COMPLETION_SHELLS" -- "$cur"))
            elif [[ $cword -eq 3 ]]; then
                COMPREPLY=($(compgen -W "--setup" -- "$cur"))
            fi
            ;;

        share)
            case "$prev" in
                --port|-p)
                    COMPREPLY=($(compgen -W "7477 7478 8080" -- "$cur"))
                    ;;
                --relay|--file)
                    ;;
                *)
                    COMPREPLY=($(compgen -W "--port -p --relay --cloud --ttl --file --profile --help" -- "$cur"))
                    ;;
            esac
            ;;

        clone)
            case "$prev" in
                --host)
                    ;;
                --port|-p)
                    COMPREPLY=($(compgen -W "7477 7478 8080" -- "$cur"))
                    ;;
                --dest|-d)
                    COMPREPLY=($(compgen -d -- "$cur"))
                    ;;
                *)
                    COMPREPLY=($(compgen -W "--host --port -p --dest -d --relay --key-secret --help" -- "$cur"))
                    ;;
            esac
            ;;

        selfinstall)
            case "$prev" in
                --dir)
                    COMPREPLY=($(compgen -d -- "$cur"))
                    ;;
                *)
                    COMPREPLY=($(compgen -W "--dir --check --help" -- "$cur"))
                    ;;
            esac
            ;;

        update)
            COMPREPLY=($(compgen -W "--check --help" -- "$cur"))
            ;;

        studio)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$STUDIO_CMDS" -- "$cur"))
            fi
            ;;

        hyperscale)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$HYPERSCALE_CMDS" -- "$cur"))
            elif [[ $cword -eq 3 ]]; then
                case "${words[2]}" in
                    config) COMPREPLY=($(compgen -W "$HYPERSCALE_CONFIG_CMDS" -- "$cur")) ;;
                    node)   COMPREPLY=($(compgen -W "$HYPERSCALE_NODE_CMDS" -- "$cur")) ;;
                esac
            fi
            ;;

        vault)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$VAULT_CMDS" -- "$cur"))
            elif [[ $cword -eq 3 ]]; then
                case "${words[2]}" in
                    mirror) COMPREPLY=($(compgen -W "$VAULT_MIRROR_CMDS" -- "$cur")) ;;
                    backup) COMPREPLY=($(compgen -W "$VAULT_BACKUP_CMDS" -- "$cur")) ;;
                    migrate) COMPREPLY=($(compgen -W "--mode --dir --help" -- "$cur")) ;;
                esac
            fi
            ;;

        node)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$NODE_CMDS" -- "$cur"))
            fi
            ;;

        config)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$CONFIG_CMDS" -- "$cur"))
            elif [[ $cword -eq 3 ]] && [[ "${words[2]}" == "cloud" ]]; then
                COMPREPLY=($(compgen -W "$CONFIG_CLOUD_CMDS" -- "$cur"))
            fi
            ;;

        cloud)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$CLOUD_CMDS" -- "$cur"))
            fi
            ;;

        push|pull)
            COMPREPLY=($(compgen -W "--file --profile --dest --id --help" -- "$cur"))
            ;;

        connect)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$CONNECT_SERVICES" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "--name --token --api-url --help" -- "$cur"))
            fi
            ;;

        provider)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$PROVIDER_CMDS" -- "$cur"))
            elif [[ $cword -eq 3 ]] && [[ "${words[2]}" == "profile" ]]; then
                COMPREPLY=($(compgen -W "$PROVIDER_PROFILE_CMDS" -- "$cur"))
            fi
            ;;

        github)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$GITHUB_CMDS" -- "$cur"))
            fi
            ;;

        vercel)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$VERCEL_CMDS" -- "$cur"))
            fi
            ;;

        supabase)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "$SUPABASE_CMDS" -- "$cur"))
            fi
            ;;

        deploy)
            COMPREPLY=($(compgen -W "--yes --dry-run --force-new --skip-github --skip-vercel --skip-supabase --github-profile --vercel-profile --supabase-profile --org --team --help" -- "$cur"))
            ;;

        *)
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
    esac

    return 0
}

complete -F _iloc_completions iloc
"#.to_string()
}

fn bash_setup_instructions() -> String {
    format!(
        "{}\n\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}",
        "Bash completion setup:".bold(),
        "  Option A — user only (no sudo):".bold(),
        "    iloc completion bash >> ~/.bash_completion",
        "    source ~/.bash_completion",
        "",
        "  Option B — system-wide (requires sudo):".bold(),
        "    iloc completion bash | sudo tee /etc/bash_completion.d/iloc",
        "",
        "  Then reload:".bold(),
        "    source ~/.bashrc",
        "  Test: type  iloc [TAB]  to see completions.",
    )
}

// ── Zsh completion ────────────────────────────────────────────

fn zsh_completion() -> String {
    r#"#compdef iloc
# iloc zsh completion
# Generated by: iloc completion zsh
#
# Installation:
#   mkdir -p ~/.zfunc
#   iloc completion zsh > ~/.zfunc/_iloc
#   Add to ~/.zshrc:  fpath=(~/.zfunc $fpath); autoload -Uz compinit && compinit

_iloc() {
    local -a commands
    commands=(
        'init:Initialise ilocker in the current directory'
        'save:Create a new snapshot'
        'undo:Restore a previous snapshot (full or selective --file)'
        'log:List all snapshots'
        'status:Show file changes since last snapshot'
        'sentinel:Manage the Sentinel shell hook'
        'selfinstall:Install iloc into the system PATH'
        'update:Check for and install iloc updates'
        'share:Share this project over the network'
        'clone:Clone a remote project by its iloc:// key'
        'transfer-status:Show the status of an in-progress transfer'
        'dashboard:Open the interactive TUI dashboard'
        'completion:Generate shell completion scripts'
        'studio:Open the VS Code command center (installs the extension if needed)'
        'hyperscale:Multi-cloud Reed-Solomon erasure-coded backup'
        'vault:Externalized vault status, migration, mirrors, backup tiers'
        'node:Join or manage the optional mesh network'
        'login:Log in to your ilocker account'
        'logout:Log out of your ilocker account'
        'whoami:Show the currently logged-in account'
        'config:Configure BYOC cloud profiles'
        'push:Push a snapshot to your own cloud (BYOC)'
        'pull:Pull a snapshot from your own cloud (BYOC)'
        'cloud:BYOC cloud usage, garbage collection, diagnostics'
        'connect:Connect a GitHub, Vercel, or Supabase account'
        'provider:Manage declarative third-party integration providers'
        'github:GitHub repos, branches, issues, PRs, releases, CI'
        'vercel:Vercel projects, deployments, env vars, domains'
        'supabase:Supabase projects, migrations, edge functions, branches'
        'deploy:Smart orchestrator across GitHub, Vercel, and Supabase'
    )

    local -a sentinel_cmds
    sentinel_cmds=(
        'init:Generate hook files and print activation instructions'
        'enable:Install the hook into your shell rc file'
        'disable:Remove the hook from your shell rc file'
        'status:Check if Sentinel is active in this shell'
        'uninstall:Remove hooks and rc file entries entirely'
    )

    local -a completion_shells
    completion_shells=(
        'bash:Generate Bash completion script'
        'zsh:Generate Zsh completion script'
        'powershell:Generate PowerShell completion script'
    )

    local -a hyperscale_cmds
    hyperscale_cmds=(
        'push:Upload with Reed-Solomon erasure coding across clouds'
        'clone:Reconstruct from distributed erasure-coded shards'
        'export:Export a sub-module to a specific cloud profile'
        'status:Show Hyperscale cloud and erasure-scheme status'
        'config:Configure the erasure coding scheme'
        'node:Run this machine as a storage contributor node'
    )

    local -a vault_cmds
    vault_cmds=(
        'status:Show vault location, size, and backup tiers'
        'migrate:Move the vault between sibling/system/custom/in-project'
        'mirror:Manage Tier 2 local mirror destinations'
        'backup:Enable or disable Tier 3 cloud/hyperscale backup'
        'verify:Verify SHA-256 integrity of all snapshots'
    )

    local -a node_cmds
    node_cmds=(
        'join:Join the optional mesh network'
        'leave:Leave the mesh network'
        'start:Start a local mesh node'
        'status:Show mesh node status'
    )

    local -a config_cmds
    config_cmds=('cloud:Manage BYOC cloud profiles')

    local -a cloud_cmds
    cloud_cmds=(
        'usage:Show storage usage for a cloud profile'
        'gc:Garbage-collect orphaned chunks and expired links'
        'doctor:Test connectivity (write + read + delete)'
        'verify:Verify integrity of all remote snapshots'
    )

    local -a connect_services
    connect_services=(
        'github:Connect a GitHub account'
        'vercel:Connect a Vercel account'
        'supabase:Connect a Supabase account'
    )

    local -a studio_cmds
    studio_cmds=(
        'open:Open the VS Code command center'
    )

    local -a provider_cmds
    provider_cmds=(
        'init:Scaffold a new provider manifest' 'validate:Validate a manifest file'
        'test:Test-run a manifest against its provider' 'install:Install a manifest file'
        'search:Search the community registry' 'publish:Prepare a manifest for registry publication'
        'list:List installed providers' 'remove:Remove an installed provider'
        'profile:Manage credential profiles for a provider'
    )

    local -a provider_profile_cmds
    provider_profile_cmds=(
        'list:List profiles for a provider' 'use:Switch the active profile'
        'remove:Remove a profile'
    )

    local -a github_cmds
    github_cmds=(
        'list:List connected GitHub profiles' 'use:Switch active GitHub profile'
        'status:Show connected account status' 'remove:Disconnect a GitHub profile'
        'repo:Repository management' 'branch:Branch management'
        'issue:Issue management' 'pr:Pull request management'
        'release:Release management' 'actions:GitHub Actions / CI'
        'secret:Actions secrets' 'collab:Collaborator management'
        'webhook:Webhook management' 'search:Search repositories'
    )

    local -a vercel_cmds
    vercel_cmds=(
        'list:List connected Vercel profiles' 'use:Switch active Vercel profile'
        'status:Show connected account status' 'remove:Disconnect a Vercel profile'
        'deploy:Deploy the current project' 'inspect:Inspect the latest deployment'
        'project:Project management' 'deployment:Deployment management'
        'env:Environment variable management' 'domain:Domain and DNS management'
        'alias:Alias management' 'secret:Legacy secret management'
        'edge:Edge Config management' 'webhook:Webhook management'
        'check:CI check management' 'team:Team management'
    )

    local -a supabase_cmds
    supabase_cmds=(
        'list:List connected Supabase profiles' 'use:Switch active Supabase profile'
        'status:Show connected account status' 'remove:Disconnect a Supabase profile'
        'org:Organization management' 'project:Project management'
        'keys:Show project API keys' 'sql:Run a raw SQL query'
        'table:Table listing' 'extension:Extension listing'
        'migration:Migration management (idempotent push)' 'function:Edge Function management'
        'secret:Edge Function secret management' 'branch:Preview branch management'
        'advisor:Security and performance advisors'
    )

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-V --version)'{-V,--version}'[Show version]' \
        '1:command:->command' \
        '*::args:->args'

    case $state in
        command)
            _describe 'iloc commands' commands
            ;;
        args)
            case $words[1] in
                save)
                    _arguments '1:message:()'
                    ;;

                undo)
                    _arguments \
                        '--file[Restore only this file]:file:_files' \
                        '(-h --help)'{-h,--help}'[Show help]' \
                        '1:snapshot_id:->snap_ids'
                    if [[ $state == snap_ids ]] && [[ -f .ilocker/iloc.db ]]; then
                        local -a snap_ids
                        snap_ids=("${(@f)$(sqlite3 .ilocker/iloc.db \
                            "SELECT id || ':' || message FROM snapshots ORDER BY created_at DESC LIMIT 20;" \
                            2>/dev/null)}")
                        _describe 'snapshot IDs' snap_ids
                    fi
                    ;;

                sentinel)
                    _arguments '1:subcommand:->sentinel_sub'
                    if [[ $state == sentinel_sub ]]; then
                        _describe 'sentinel commands' sentinel_cmds
                    fi
                    ;;

                completion)
                    _arguments \
                        '1:shell:->shell_name' \
                        '--setup[Print setup instructions]'
                    if [[ $state == shell_name ]]; then
                        _describe 'shells' completion_shells
                    fi
                    ;;

                share)
                    _arguments \
                        '(-p --port)'{-p,--port}'[TCP port]:port:(7477 7478 8080)' \
                        '--relay[Relay host for NAT traversal]:relay:()' \
                        '--cloud[Generate an async cloud share link]' \
                        '--ttl[Cloud link expiry in hours]:hours:()' \
                        '--file[Restrict to specific files]:file:_files' \
                        '--profile[Cloud profile to use]:profile:()' \
                        '(-h --help)'{-h,--help}'[Show help]'
                    ;;

                clone)
                    _arguments \
                        '1:project_key:(iloc://)' \
                        '--host[Sharer host/IP]:host:()' \
                        '--relay[Relay host for NAT traversal]:relay:()' \
                        '--key-secret[Decryption key for cloud links]:key:()' \
                        '(-p --port)'{-p,--port}'[TCP port]:port:(7477 7478 8080)' \
                        '(-d --dest)'{-d,--dest}'[Destination directory]:dest:_directories' \
                        '(-h --help)'{-h,--help}'[Show help]'
                    ;;

                selfinstall)
                    _arguments \
                        '--dir[Installation directory]:dir:_directories' \
                        '--check[Check if already in PATH]' \
                        '(-h --help)'{-h,--help}'[Show help]'
                    ;;

                update)
                    _arguments \
                        '--check[Check only, do not install]' \
                        '(-h --help)'{-h,--help}'[Show help]'
                    ;;

                studio)
                    _arguments '1:subcommand:->studio_sub'
                    if [[ $state == studio_sub ]]; then
                        _describe 'studio commands' studio_cmds
                    fi
                    ;;

                hyperscale)
                    _arguments '1:subcommand:->hyperscale_sub' '*::hargs:->hargs'
                    if [[ $state == hyperscale_sub ]]; then
                        _describe 'hyperscale commands' hyperscale_cmds
                    fi
                    ;;

                vault)
                    _arguments '1:subcommand:->vault_sub'
                    if [[ $state == vault_sub ]]; then
                        _describe 'vault commands' vault_cmds
                    fi
                    ;;

                node)
                    _arguments '1:subcommand:->node_sub'
                    if [[ $state == node_sub ]]; then
                        _describe 'node commands' node_cmds
                    fi
                    ;;

                config)
                    _arguments '1:subcommand:->config_sub'
                    if [[ $state == config_sub ]]; then
                        _describe 'config commands' config_cmds
                    fi
                    ;;

                cloud)
                    _arguments '1:subcommand:->cloud_sub'
                    if [[ $state == cloud_sub ]]; then
                        _describe 'cloud commands' cloud_cmds
                    fi
                    ;;

                push|pull)
                    _arguments \
                        '--file[Restrict to specific files]:file:_files' \
                        '--profile[Cloud profile to use]:profile:()' \
                        '--dest[Destination directory (pull only)]:dest:_directories' \
                        '(-h --help)'{-h,--help}'[Show help]'
                    ;;

                connect)
                    _arguments \
                        '1:service:->connect_service' \
                        '--name[Profile name]:name:()' \
                        '--token[Token (non-interactive)]:token:()' \
                        '--api-url[Custom API URL]:url:()' \
                        '(-h --help)'{-h,--help}'[Show help]'
                    if [[ $state == connect_service ]]; then
                        _describe 'services' connect_services
                    fi
                    ;;

                provider)
                    _arguments '1:subcommand:->provider_sub' '*::pargs:->pargs'
                    if [[ $state == provider_sub ]]; then
                        _describe 'provider commands' provider_cmds
                    elif [[ $state == pargs ]] && [[ $words[1] == profile ]]; then
                        _arguments '1:subcommand:->provider_profile_sub'
                        if [[ $state == provider_profile_sub ]]; then
                            _describe 'provider profile commands' provider_profile_cmds
                        fi
                    fi
                    ;;

                github)
                    _arguments '1:subcommand:->github_sub'
                    if [[ $state == github_sub ]]; then
                        _describe 'github commands' github_cmds
                    fi
                    ;;

                vercel)
                    _arguments '1:subcommand:->vercel_sub'
                    if [[ $state == vercel_sub ]]; then
                        _describe 'vercel commands' vercel_cmds
                    fi
                    ;;

                supabase)
                    _arguments '1:subcommand:->supabase_sub'
                    if [[ $state == supabase_sub ]]; then
                        _describe 'supabase commands' supabase_cmds
                    fi
                    ;;

                deploy)
                    _arguments \
                        '--yes[Skip confirmation]' \
                        '--dry-run[Show the plan without executing]' \
                        '--force-new[Ignore name matches, always create new]' \
                        '--skip-github[Skip the GitHub step]' \
                        '--skip-vercel[Skip the Vercel step]' \
                        '--skip-supabase[Skip the Supabase step]' \
                        '--github-profile[GitHub profile to use]:profile:()' \
                        '--vercel-profile[Vercel profile to use]:profile:()' \
                        '--supabase-profile[Supabase profile to use]:profile:()' \
                        '--org[Supabase organization override]:org:()' \
                        '--team[Vercel team override]:team:()' \
                        '(-h --help)'{-h,--help}'[Show help]'
                    ;;

                log|status|init|dashboard|transfer-status|whoami|login|logout)
                    _arguments '(-h --help)'{-h,--help}'[Show help]'
                    ;;
            esac
            ;;
    esac
}

_iloc "$@"
"#.to_string()
}

fn zsh_setup_instructions() -> String {
    format!(
        "{}\n\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}",
        "Zsh completion setup:".bold(),
        "  1. Create the zfunc directory:".bold(),
        "       mkdir -p ~/.zfunc",
        "",
        "  2. Install the completion file:".bold(),
        "       iloc completion zsh > ~/.zfunc/_iloc",
        "",
        "  3. Add to ~/.zshrc (if not already present):".bold(),
        "       fpath=(~/.zfunc $fpath)",
        "       autoload -Uz compinit && compinit",
        "",
        "  4. Reload:  source ~/.zshrc",
    )
}

// ── PowerShell completion ──────────────────────────────────────
//
// Utilise Register-ArgumentCompleter -Native, le mécanisme standard
// de PowerShell pour la complétion d'une commande externe (identique
// à ce que fait par exemple `Import-Module` pour `git`, `docker`, …).
// Couvre les mêmes commandes/sous-commandes que bash_completion() et
// zsh_completion() ci-dessus, avec complétion sur mot partiel
// (ex: `iloc sent<TAB>` -> `sentinel`) et sur 3 niveaux d'imbrication
// (ex: `iloc hyperscale config <TAB>` -> `init show validate`).
// Validé avec TabExpansion2 sous PowerShell 7.6 avant intégration ici.
fn powershell_completion() -> String {
    r#"# iloc PowerShell completion
# Generated by: iloc completion powershell
# Add to your $PROFILE: iloc completion powershell >> $PROFILE

Register-ArgumentCompleter -Native -CommandName 'iloc' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @(
        'init','save','undo','log','status','sentinel','selfinstall','update',
        'share','clone','transfer-status','dashboard','completion','studio',
        'hyperscale','vault','node','login','logout','whoami','config','push',
        'pull','cloud','connect','provider','github','vercel','supabase','deploy'
    )
    $sentinelCmds         = 'init','enable','disable','status','uninstall'
    $completionShells     = 'bash','zsh','powershell'
    $hyperscaleCmds       = 'push','clone','export','status','config','node'
    $hyperscaleConfigCmds = 'show','init','validate'
    $hyperscaleNodeCmds   = 'start','stop','status'
    $vaultCmds            = 'status','migrate','mirror','backup','verify'
    $vaultMirrorCmds      = 'add','remove','sync'
    $vaultBackupCmds      = 'enable-cloud','disable-cloud','enable-hyperscale','disable-hyperscale'
    $nodeCmds             = 'join','leave','start','status'
    $configCmds           = 'cloud'
    $configCloudCmds      = 'add','list','use','remove'
    $cloudCmds            = 'usage','gc','doctor','verify'
    $connectServices      = 'github','vercel','supabase'
    $studioCmds           = 'open','manifest'
    $providerCmds         = 'init','validate','test','install','search','publish','list','remove','profile'
    $providerProfileCmds  = 'list','use','remove'
    $githubCmds           = 'list','use','status','remove','repo','branch','issue','pr','release','actions','secret','collab','webhook','search'
    $vercelCmds           = 'list','use','status','remove','deploy','inspect','project','deployment','env','domain','alias','secret','edge','webhook','check','team'
    $supabaseCmds         = 'list','use','status','remove','org','project','keys','sql','table','extension','migration','function','secret','branch','advisor'

    $tokens = $commandAst.CommandElements | ForEach-Object { $_.Extent.Text }

    # Si le dernier token correspond exactement au mot en cours de frappe
    # (pas encore suivi d'un espace), on l'exclut du contexte de navigation :
    # 'iloc sent' doit compléter le NIVEAU 1 (comme 'iloc '), pas chercher
    # une sous-commande du groupe 'sent' qui n'existe pas encore.
    $context = $tokens
    if ($context.Count -gt 0 -and $wordToComplete -ne '' -and $context[-1] -eq $wordToComplete) {
        $context = $context[0..($context.Count - 2)]
    }

    $result = @()

    if ($context.Count -le 1) {
        $result = $commands
    }
    elseif ($context.Count -eq 2) {
        switch ($context[1]) {
            'sentinel'   { $result = $sentinelCmds }
            'completion' { $result = $completionShells }
            'studio'     { $result = $studioCmds }
            'hyperscale' { $result = $hyperscaleCmds }
            'vault'      { $result = $vaultCmds }
            'node'       { $result = $nodeCmds }
            'config'     { $result = $configCmds }
            'cloud'      { $result = $cloudCmds }
            'connect'    { $result = $connectServices }
            'provider'   { $result = $providerCmds }
            'github'     { $result = $githubCmds }
            'vercel'     { $result = $vercelCmds }
            'supabase'   { $result = $supabaseCmds }
            default      { $result = @() }
        }
    }
    elseif ($context.Count -eq 3) {
        switch ("$($context[1]) $($context[2])") {
            'hyperscale config' { $result = $hyperscaleConfigCmds }
            'hyperscale node'   { $result = $hyperscaleNodeCmds }
            'vault mirror'      { $result = $vaultMirrorCmds }
            'vault backup'      { $result = $vaultBackupCmds }
            'config cloud'      { $result = $configCloudCmds }
            'provider profile'  { $result = $providerProfileCmds }
            default             { $result = @() }
        }
    }

    $result |
        Where-Object { $_ -like "$wordToComplete*" } |
        Sort-Object |
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
"#.to_string()
}

fn powershell_setup_instructions() -> String {
    format!(
        "{}\n\n{}\n{}\n{}\n{}\n{}\n{}\n{}",
        "PowerShell completion setup:".bold(),
        "  1. Create your profile if it doesn't exist yet:".bold(),
        "       if (!(Test-Path $PROFILE)) { New-Item -ItemType File -Force $PROFILE }",
        "",
        "  2. Append the completion script to it:".bold(),
        "       iloc completion powershell >> $PROFILE",
        "",
        "  3. Reload:  . $PROFILE\n  Test: type  iloc <TAB>  to see completions.",
    )
}
